package com.machine.pages;

public enum Page {
    INDEX, REGISTRATION, CASHIER, SENIOR_CASHIER, PRODUCT_OBSERVER, CASHBOX, BILL,
    ADD_PRODUCT_TO_BILL_N, ADD_PRODUCT_TO_BILL_C, MAKE_X, MAKE_Z, PRODUCTS, ADD_PRODUCT_TO_WAREHOUSE, UPDATE_PRODUCT_INFO
}
